version: "3.9"

x-airflow-common: &airflow-common
  build:
    context: .
    dockerfile: Dockerfile
  environment:
    AIRFLOW__CORE__EXECUTOR: LocalExecutor
    AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://postgres:postgres@postgres:5432/airflow
    AIRFLOW__CORE__AUTH_MANAGER: airflow.providers.fab.auth_manager.fab_auth_manager.FabAuthManager
    AIRFLOW__CORE__FERNET_KEY: 'axAcsyAFw6cU-ktCUzY3U-hF4dZBLFTK5qQUJC8fGyI='
    AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
    AIRFLOW__API__SECRET_KEY: '3cb0160b06c99816fafbc8e597e8179a56a7de4eb33dd38139381519215d8ed2'
    _AIRFLOW_WWW_USER_CREATE: 'true'
    _AIRFLOW_WWW_USER_USERNAME: 'admin'
    _AIRFLOW_WWW_USER_PASSWORD: 'admin'
    _AIRFLOW_WWW_USER_FIRSTNAME: 'Admin'
    _AIRFLOW_WWW_USER_LASTNAME: 'User'
    _AIRFLOW_WWW_USER_EMAIL: 'admin@example.com'
    _AIRFLOW_WWW_USER_ROLE: 'Admin'
  volumes:
    - ./dags:/opt/airflow/dags
    - ./logs:/opt/airflow/logs
    - ./plugins:/opt/airflow/plugins
    - /home/strutz/Desktop/Projects/renewable-generation/src/jobs:/opt/airflow/scripts
  networks:
    - fraud-network
  depends_on:
    postgres:
      condition: service_healthy

services:
  mongodb:
    image: mongo:7
    container_name: mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: appdb
    volumes:
      - mongo_data:/data/db
    networks:
      - fraud-network

  postgres:
    image: pgvector/pgvector:pg16
    container_name: postgres-local
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: airflow
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - fraud-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  airflow-init:
    <<: *airflow-common
    container_name: airflow-init
    entrypoint: /bin/bash
    command:
      - -c
      - |
        airflow db migrate && \
        airflow fab-db migrate   # ✅ era fab-db init

  airflow-webserver:
    <<: *airflow-common
    container_name: airflow-webserver
    restart: unless-stopped
    ports:
      - "8081:8080"
    command: api-server
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 5

  airflow-scheduler:
    <<: *airflow-common
    container_name: airflow-scheduler
    restart: unless-stopped
    command: scheduler

  airflow-dag-processor:
    <<: *airflow-common
    container_name: airflow-dag-processor
    restart: unless-stopped
    command: dag-processor
    depends_on:
      postgres:
        condition: service_healthy
      airflow-init:
        condition: service_completed_successfully

  localstack:
    image: localstack/localstack:3.8.1
    container_name: localstack
    ports:
      - "4566:4566"
    environment:
      - AWS_DEFAULT_REGION=us-east-1
      - LOCALSTACK_HOST=localstack
    volumes:
      - "./localstack/init:/etc/localstack/init/ready.d"
      - "localstack_data:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - network

volumes:
  mongo_data:
  redis_data:
  postgres_data:
  localstack_data:

networks:
  aws-network:
    driver: bridge